name: Clog
main: org.dyndns.pamelloes.Clog.Clog
version: 0.4
description: Clog affects users' permissions based on whether or not they use Spoutcraft.
depend: [Spout]
softdepend: [PermissionsBukkit, PermissionsEx, bPermissions]
commands:
  hasspout:
    description: Find out if someone is using Spoutcraft.
    permission: clog.checkspout
    usage: /<command> player
