name: Clog
main: org.dyndns.pamelloes.Clog.Clog
version: 0.1.2
description: Clog affects users' permissions based on whether or not they use Spoutcraft.
depend: [Spout]
softdepend: [PermissionsBukkit]